# -*- coding: utf-8 -*-
"""ViT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2qwGwsZV65tstkZk3hDSR_wiEs9TZnF
"""

from google.colab import drive
drive.mount('/content/drive')

# Importing the required libraries
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import os

# Device configuration - deciding whether to run the training on cpu or gpu
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

if not os.path.exists("tiny-imagenet-200"):
    !wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
    !unzip -q tiny-imagenet-200.zip

!ls tiny-imagenet-200/val

import shutil

val_dir = "tiny-imagenet-200/val"
images_dir = os.path.join(val_dir, "images")
val_annotations = os.path.join(val_dir, "val_annotations.txt")

with open(val_annotations) as f:
  lines = f.readlines()

for line in lines:
      img, cls = line.split("\t")[:2]
      cls_dir = os.path.join(val_dir, cls)
      os.makedirs(cls_dir, exist_ok=True) # Ensure target class directory exists

      src_path = os.path.join(images_dir, img)
      dst_path = os.path.join(cls_dir, img)

      if not os.path.exists(src_path):
          # If source does not exist, check if it's already in the destination
          if os.path.exists(dst_path):
              print(f"Image '{img}' already moved to '{cls_dir}'. Skipping.")
          else:
              print(f"Warning: Source image '{src_path}' not found for '{img}'. It might be missing or the dataset structure is unexpected.")
      else:
          # If source exists, and destination does not, move it.
          if not os.path.exists(dst_path):
              shutil.move(src_path, dst_path)
          else:
              print(f"Image '{img}' already exists in '{cls_dir}'. Skipping move.")

    # Only attempt to remove images_dir if it exists and is empty after processing
if os.path.exists(images_dir):
  if not os.listdir(images_dir):
      os.rmdir(images_dir)
  else:
      print(f"Warning: '{images_dir}' is not empty after processing. Some files might not have been moved or were not part of the annotations.")

transform_train = transforms.Compose(
    [ transforms.RandomResizedCrop(224),
      transforms.RandomHorizontalFlip(),
      transforms.ToTensor(),
      transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                  std=[0.229, 0.224, 0.225])])

transform_val = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                  std=[0.229, 0.224, 0.225])])

train_dataset = datasets.ImageFolder( "tiny-imagenet-200/train", transform=transform_train )
val_dataset = datasets.ImageFolder( "tiny-imagenet-200/val", transform=transform_val )

# Hyper-parameters
batch_size = 64
learning_rate = 0.0003
num_epochs = 10

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

# import matplotlib.pyplot as plt

# # View some of the images from the dataset using matplotlib
# # Get a batch
# examples = iter(val_loader)
# example_data, example_targets = next(examples)

# class_names = train_dataset.classes

# plt.figure(figsize=(8,5))

# for i in range(6):
#     plt.subplot(2, 3, i+1)

#     img = example_data[i].permute(1, 2, 0)  # C,H,W → H,W,C
#     plt.imshow(img)
#     plt.title(class_names[example_targets[i]])
#     plt.axis("off")

# plt.show()

# Patch Embedding
class PatchEmbedding(nn.Module):
    def __init__(self, img_size=224, patch_size=16, in_channels=3, embed_dim=128):
        super().__init__()

        self.num_patches = (img_size // patch_size) ** 2

        self.projection = nn.Conv2d(
            in_channels,
            embed_dim,
            kernel_size=patch_size,
            stride=patch_size
        )

    def forward(self, x):
        x = self.projection(x)

        # (B, E, H, W) -> (B, N, E)
        x = x.flatten(2)
        x = x.transpose(1, 2)

        return x


# Vision Transformer
class SimpleViT(nn.Module):
    def __init__(
        self,
        img_size=32,
        patch_size=4,
        num_classes=10,
        embed_dim=128,
        depth=4,
        num_heads=4,
        mlp_dim=256
    ):
        super().__init__()

        self.patch_embed = PatchEmbedding(
            img_size,
            patch_size,
            3,
            embed_dim
        )

        num_patches = self.patch_embed.num_patches

        # CLS token
        self.cls_token = nn.Parameter(
            torch.randn(1, 1, embed_dim)
        )

        # Positional embeddings
        self.pos_embedding = nn.Parameter(
            torch.randn(1, num_patches + 1, embed_dim)
        )

        # Transformer encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=num_heads,
            dim_feedforward=mlp_dim,
            dropout=0.1,
            batch_first=True
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=depth
        )

        # Classification head
        self.mlp_head = nn.Linear(embed_dim, num_classes)

    def forward(self, x):

        x = self.patch_embed(x)

        batch_size = x.shape[0]

        cls_tokens = self.cls_token.expand(batch_size, -1, -1)

        x = torch.cat((cls_tokens, x), dim=1)

        x = x + self.pos_embedding

        x = self.transformer(x)

        cls_output = x[:, 0]

        out = self.mlp_head(cls_output)

        return out

model = SimpleViT(
    img_size=224,
    patch_size=16,
    num_classes=200,
    embed_dim=256,
    depth=4,
    num_heads=4,
    mlp_dim=512
)

model = model.to(device)

cost = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Printing how many steps are remaining when training
total_steps = len(train_loader)

for current_epoch in range(num_epochs):
        model.train()
        for idx, (train_x, train_label) in enumerate(train_loader):
            train_x = train_x.to(device)
            train_label = train_label.to(device)

            # Forward pass
            predict_y = model(train_x.float())
            loss = cost(predict_y, train_label.long())

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            if (idx+1) % 400 == 0:
                print (f'Epoch [{current_epoch+1}/{num_epochs}], Step [{idx+1}/{total_steps}], Loss: {loss.item():.4f}')

print('Finished Training')

# Set the model to evaluation mode
model.eval()

# In the test phase, we don't compute gradients (for memory efficiency)
with torch.no_grad():
    all_correct_num = 0
    all_sample_num = 0
    for idx, (test_x, test_label) in enumerate(val_loader):
        test_x = test_x.to(device)
        test_label = test_label.to(device)
        predict_y = model(test_x.float()).detach()
        predict_y =torch.argmax(predict_y, dim=-1)
        current_correct_num = predict_y == test_label
        all_correct_num += torch.sum(current_correct_num).item()
        all_sample_num += current_correct_num.shape[0]
    acc = (all_correct_num / all_sample_num) * 100
    print('Accuracy of the baseline model: {:.3f}'.format(acc), flush=True)
    print("Model finished training")

# Save model and optimizer states
torch.save({
    'epoch': num_epochs,  # Track the current epoch
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': cost,  # Optionally save the last loss
}, '/content/drive/MyDrive/Colab Notebooks/Tasks-DL/vit.pth')
print("Model saved successfully")

from google.colab import drive
drive.mount('/content/drive')

# Importing the required libraries
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torchvision.models import alexnet
from torch.utils.data import DataLoader
import os

# Device configuration - deciding whether to run the training on cpu or gpu
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters
batch_size = 64
learning_rate = 1e-4
num_epochs = 10

if not os.path.exists("tiny-imagenet-200"):
    !wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
    !unzip -q tiny-imagenet-200.zip

!ls tiny-imagenet-200/val

import shutil

val_dir = "tiny-imagenet-200/val"
images_dir = os.path.join(val_dir, "images")
val_annotations = os.path.join(val_dir, "val_annotations.txt")

with open(val_annotations) as f:
  lines = f.readlines()

for line in lines:
      img, cls = line.split("\t")[:2]
      cls_dir = os.path.join(val_dir, cls)
      os.makedirs(cls_dir, exist_ok=True) # Ensure target class directory exists

      src_path = os.path.join(images_dir, img)
      dst_path = os.path.join(cls_dir, img)

      if not os.path.exists(src_path):
          # If source does not exist, check if it's already in the destination
          if os.path.exists(dst_path):
              print(f"Image '{img}' already moved to '{cls_dir}'. Skipping.")
          else:
              print(f"Warning: Source image '{src_path}' not found for '{img}'. It might be missing or the dataset structure is unexpected.")
      else:
          # If source exists, and destination does not, move it.
          if not os.path.exists(dst_path):
              shutil.move(src_path, dst_path)
          else:
              print(f"Image '{img}' already exists in '{cls_dir}'. Skipping move.")

# Only attempt to remove images_dir if it exists and is empty after processing
if os.path.exists(images_dir):
  if not os.listdir(images_dir):
      os.rmdir(images_dir)
  else:
      print(f"Warning: '{images_dir}' is not empty after processing. Some files might not have been moved or were not part of the annotations.")


transform_train = transforms.Compose(
    [ transforms.RandomResizedCrop(224),
      transforms.RandomHorizontalFlip(),
      transforms.ToTensor(),
      transforms.Normalize((0.485, 0.456, 0.406),(0.229, 0.224, 0.225))])

transform_val = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406),(0.229, 0.224, 0.225))])

train_dataset = datasets.ImageFolder( "tiny-imagenet-200/train", transform=transform_train )
val_dataset = datasets.ImageFolder( "tiny-imagenet-200/val", transform=transform_val )

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

import matplotlib.pyplot as plt

# View some of the images from the dataset using matplotlib
# Get a batch
examples = iter(val_loader)
example_data, example_targets = next(examples)

class_names = train_dataset.classes

plt.figure(figsize=(8,5))

for i in range(6):
    plt.subplot(2, 3, i+1)

    img = example_data[i].permute(1, 2, 0)  # C,H,W → H,W,C
    plt.imshow(img)
    plt.title(class_names[example_targets[i]])
    plt.axis("off")

plt.show()

from torchvision import models
import torch.nn as nn

model = models.alexnet(pretrained=True)

# Replace classifier
model.classifier[6] = nn.Linear(4096, 200) # 200 classes
model = model.to(device)

# freeze features
for param in model.features.parameters():
    param.requires_grad = False

cost = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Printing how many steps are remaining when training
total_steps = len(train_loader)

for current_epoch in range(num_epochs):
        model.train()
        for idx, (train_x, train_label) in enumerate(train_loader):
            train_x = train_x.to(device)
            train_label = train_label.to(device)

            # Forward pass
            predict_y = model(train_x.float())
            loss = cost(predict_y, train_label.long())

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            if (idx+1) % 400 == 0:
                print (f'Epoch [{current_epoch+1}/{num_epochs}], Step [{idx+1}/{total_steps}], Loss: {loss.item():.4f}')

print('Finished Training')

# Set the model to evaluation mode
model.eval()

# In the test phase, we don't compute gradients (for memory efficiency)
with torch.no_grad():
    all_correct_num = 0
    all_sample_num = 0
    for idx, (test_x, test_label) in enumerate(val_loader):
        test_x = test_x.to(device)
        test_label = test_label.to(device)
        predict_y = model(test_x.float()).detach()
        predict_y =torch.argmax(predict_y, dim=-1)
        current_correct_num = predict_y == test_label
        all_correct_num += torch.sum(current_correct_num).item()
        all_sample_num += current_correct_num.shape[0]
    acc = (all_correct_num / all_sample_num) * 100
    print('Accuracy of the baseline model: {:.3f}'.format(acc), flush=True)
    print("Model finished training")
    print(f"✅ Result logged: lr={learning_rate}, batch_size={batch_size}, acc={acc:.3f}%")

# Accuracy of the baseline model: 55.200 - unfrozen
# Model finished training

# Accuracy of the baseline model: 57.000 - frozen
# Model finished training

# Finished Training
# Accuracy of the baseline model: 24.640
# Model finished training